### ISSUE TITLE
[CI] ci: implement unit tests for roles with Molecule

### ISSUE THREAD

**Issue by btravouillon** [bluebanquise/bluebanquise#165]
Issue to track the work to implement CI/CD unit tests of the roles with [Molecule](https://molecule.readthedocs.io/en/latest/). Please refer to the instructions below. You can use PR #242 as an example.

## Core roles
- [x] bluebanquise (#221)
- [x] conman (#170) (#463)
- [x] dhcp_server (#413)
- [x] display_tuning (#175)
- [x] dns_client (#175)
- [x] dns_server (#162)
- [ ] hosts_file (Cannot be tested with molecule, see: #462)
- [x] log_client (#187)
- [x] log_server (#187)
- [x] nfs_client (#412)
- [x] nfs_server (#412) 
- [ ] nic (#512)
- [x] pxe_stack (#439)
- [x] repositories_client (#171)
- [x] repositories_server (#462)
- [x] set_hostname (#511)
- [x] ssh_master (#242)
- [x] ssh_slave (#462)
- [x] time (#162)

## Advanced core roles
- [x] advanced_dhcp_server (#428)
- [x] advanced_dns_server (#438)

## Addons roles
- [ ] clone
- [x] clustershell (#174)
- [ ] diskless
- [ ] nic_nmcli
- [ ] ofed
- [ ] ofed_sm
- [ ] openldap_client
- [ ] openldap_server
- [ ] prometheus_client (#430)
- [ ] prometheus_server (#430)
- [ ] report
- [ ] slurm
- [x] users_basic (#174)

## How to

For developers, install virtualenv in your environment:

`$ pip install --user virtualenv`

At the root of your git clone, create a new virtual environment in directory venv and activate it:

```
$ virtualenv venv-molecule
$ source venv-molecule/bin/activate
(venv-molecule) $ 
```
Install the required modules in the virtual environment:

`(venv-molecule) $ pip install 'molecule[docker]>3' ansible-lint flake8`

Change your current directory to the role you want to update and initialize the default molecule scenario:

```
(venv-molecule) $ cd roles/core/conman/
(venv-molecule) $ molecule init scenario --role-name conman
--> Initializing new scenario default...
Initialized scenario in /git/bluebanquise/roles/core/conman/molecule/default successfully.
```
Tune, commit, test, open a PR.

Once completed, deactivate your virtual environment:

```
(venv-molecule) $ deactivate 
$ 
```
Note: If you run Fedora 31, [Docker will not run by default due to switch to cgroups v2](https://fedoraproject.org/wiki/Common_F31_bugs#Docker_package_no_longer_available_and_will_not_run_by_default_.28due_to_switch_to_cgroups_v2.29), however it's still possible to run most of the tests locally using the podman driver (`molecule create -d podman`).

**Comment by strus38** [comment]
PR 174 for addons/clustershell and addons/users_basic.

**Comment by btravouillon** [comment]
Did you drop all the molecule tests?

**Comment by oxedions** [comment]
Temporary only. I would like to reintroduce them as they allow fine grained tests, which are better than "global" ones. I just miss bandwidth to update and maintain them for now 😔 so my plan is to wait for 2.0 alpha version converged to import molecules test from 1.x branches.
Main objective of 2.0 is to be rock stable, and only per Role tests can achieve that (to test all variables).

**Comment by oxedions** [comment]
Most of the tests have been back-ported to the new workflow, and I will continue to improve it. We can close this issue.
