### ISSUE TITLE
General features requests dashboard

### ISSUE THREAD

**Issue by oxedions** [bluebanquise/bluebanquise#182]
# General features planed for 1.4.0

## Focus on

**Core**
- [ ] bootset dedicated kernel params (ability to add dedicated kernel params at bootset invocation. Nodes files already have this variable).
- [ ] nmcli replacement for nic role (replace current templates by nmcli module).
- [ ] Advanced routing for network (default gateway in case of multiple, routing in multiple icebergs, etc).

**Addons**
- [ ] Rewrite diskless role to handle plugins.
- [ ] Ssh jump in multi iceberg managements (allows a single point of management or playbook execution).

**Tools**
- [ ] Enhance bluebanquise-playbook with spread task capability (ability to use command line or YAML file to spread a playbook execution over executors, in case of massive deployment).

**Doc**
- [ ] Enhance Advanced DNS server role readme.
- [ ] bootset man.
- [ ] Add more stories.
- [ ] Improve report role.

## If possible
**Core**
- [ ] Redo PXE part for Fedora, OpenSuse, Debian and Ubuntu. Only support PXE of these distribution over client nodes for now.

**Addons**
- [ ] Clean clone addon.
- [x] Basic Lmod role.

# General features planed for 1.3

1.3 is targeted to be a quality release. No major changes in core.

**Architecture/General**
- [x] Switch to replace HB
  - [x] merge networks (#252)
  - [x] rename all_equipment (#252)
  - [x] header in global file
  - [x] handle empty dict if not server
- [x] Add j2 into github root inventory (allows updates) (#269)
- [x] Tasks naming convention

**Core**
- Repositories
  - [x] Advanced core repositories
  - [x] Deprecate external_repositories (#270)
- [x] Role to enforce equipment_profile
- bootset
  - [x] status
- DNS
  - [x] Advanced DNS
- [x] Firewall handling in roles (#238)
- [x] PXE nodefile re-ordering

**Addons**
- [x] Finish and validate Prometheus roles (monitoring, @oxedions )
- [x] Login nodes addon role
- [x] Power management tool

**Doc**
- [x] password generation
- [x] facts/include/etc missing from training
- [x] Clean example inventories (#252)
- [x] equipment_profiles values are not properly explained in the documentation, and available values are not provided (@oxedions )

# General features requested delayed

- [ ] [DHCP failover](https://kb.isc.org/docs/aa-01356)
- [ ] Rewrite ldap_client/server role (and rename it) to use 389 and handle cockpit related plugin
- [ ] Full core support for Ubuntu 20.04 (@johnnykeats )
- [ ] Full core support for OpenSuse Leap 15.1 (@oxedions https://github.com/bluebanquise/bluebanquise/projects/3 https://github.com/bluebanquise/bluebanquise/pull/213 :fire:)
- [x] Masquerading role

Requests from external users:

- [x] Add some "how to" scenarios in the documentation
    - [x] Add a new host
    - [x] Update cluster
- [x] Add in readme of each role input variables (mandatory and optional) and output files
- [ ] Feature so that each role can "tag" an host when executing, with time and its current version (tracking)
- [ ] Add an ansible-playbook-grapher render in each role (task level)

**Comment by actatux** [comment]
Should we continue to implement gathering of OS vars for next release? (#173, #179)

**Comment by oxedions** [comment]
Sorry for delay. Yes we should :-)

**Comment by actatux** [comment]
For the record, I add DHCP failover in the feat req list for next release.

**Comment by oxedions** [comment]
First, thanks for adding all of these into the project panel. I will also start using it.

Secondly, ok for DHCP failover mechanism. :-)

**Comment by actatux** [comment]
Quick thought: wondering if we should rename role `ansible` to `bluebanquise` before the release? The purpose is to install the tools required to run bluebanquise on a management/service node, isn't it?

**Comment by oxedions** [comment]
Yes it is. So it makes sense to rename it BlueBanquise indeed.

**Comment by johnnykeats** [comment]
After long discussion yesterday, go back to previous plan: 1.3 is a quality release of 1.2. No major core modifications should have been made. What is done is done and kept. Now stabilize and clean.

1.4 will be dedicated to OpenSuse integration. No other core modifications for 1.4, as OpenSuse integrations brings enough changes.

**Comment by johnnykeats** [comment]
@actatux May I reuse your firewall PR, for the cleaning process?

@oxedions Can you upload your changes in OpenSuse branch?

**Comment by actatux** [comment]
Not sure to understand what you want to re-use, but yes, go ahead :-).

**Comment by johnnykeats** [comment]
Will add in each role (readme) optional firewall data (will rely on yours).
Allows later easy add of firewall addon.

**Comment by actatux** [comment]
I'm working on a PR without any firewall role which would allow to open the requested services/ports in the default zone (public). Each role will remain isolated. The configuration will work out-of-the-box when `firewall: true`.

**Comment by johnnykeats** [comment]
Please, no firewall related tasks in roles, if this is your target.

Firewall addon role must handle that, using zones and related interfaces, services, ports.

Example (not final), **at host_vars level**:

```
firewall:
  zones:
    external:
      interfaces:
        - eth1
      masquerade: true
      services:
        - ssh
        - dhclient
      ports:
        - 80/tcp
        - 443/tcp
    trusted:
      interfaces:
        - eth1
```
 
Roles must not include their main firewall related tasks.

**Comment by actatux** [comment]
To configure a service for production, one must install software (package), enable/start the daemon (service), eventually add some SELinux rules (seport, seboolean, etc) and open some ports (firewall). Ansible provides modules for all these tasks.

I don't understand why the firewall should be handled differently. Can you explain please?

**Comment by johnnykeats** [comment]
You got a point.

Attempted to find a simple way to manage zones, none for now.
Default (public) is ok, and zones management can be added later (keeping `| default('public')` ).

Please proceed.
Remember Centos and OpenSuse are firewalld, but not Ubuntu (ufw). Not mandatory to handle for now, but if needed please keep in mind this aspect.

**Comment by johnnykeats** [comment]
Firewall is not in the list. Adding it. Urgent need?

**Comment by actatux** [comment]
We need it for our solution indeed. I will try to find some time today or tomorrow to open a draft PR.

**Comment by johnnykeats** [comment]
Ok, moving it to 1.3 then. Ox told me about this need. No direct impact on roles, ok for me on 1.3.

**Comment by actatux** [comment]
Firewall discussion: #238.

**Comment by johnnykeats** [comment]
1 proposal, 1 survey:

1. Lets cancel core repositories and core dns. Current roles are ok.
2. Should we remove ansible.cfg file from bluebanquise, and only provide way to configure it in documentation and/or provide a script to automatically do it? This, in order to prevent issues in case of Ansible version update (new features/parts missing in our provided ansible.cfg file).

**Comment by actatux** [comment]
1. OK

2. I like the way it works currently.
User does not have to mind about setting roles_path, which is internal to BlueBanquise. The ansible.cfg is installed in /etc/bluebanquise/ right now, so an update of ansible would not replace the file anyway, it would still be user responsibility.
Even if one install BB into /etc/ansible/, the content of the directory is %config(noreplace) in ansible.spec for EL-like distro, so a local change to the file would not be overwritten by an update (new features/parts would be missing as well).
To be honest, that's a question I asked myself a few weeks ago about all the template files we provide. Most of these files are provided by packages, however we overwrite these and can miss some new features/config change as well. I don't see any simple way to solve this.

3. (question related to ansible.cfg): could we consider using [relative paths in the configuration file](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#relative-paths-for-configuration)?
```
inventory     = inventory
roles_path    = roles/core:roles/addons:roles/customs:roles/advanced-core
```

**Comment by oxedions** [comment]
1. OK
2. Same, we will just have to ensure time to time our file is not out of sync with current versions.
3. Yes, agreed !

**Comment by oxedions** [comment]
@johnnykeats I finalized the scalability tuning. As it is mandatory for my company, I will open a draft PR for it, and we will discuss about it.

**Comment by johnnykeats** [comment]
@oxedions 

See some missing things in the 1.3 RC1:
- A changelog
- The speed up template mechanism
- The bootset dedicated parameters

I assume you postpone the last 2 for 1.3.1 as they are already in the stack, but need to be fixed. However, we should provide a changelog for the final 1.3.0. Would make it "professional".
Not urgent of course, august should be quiet.

**Comment by actatux** [comment]
:+1: 

The [version in the rpmspec](https://github.com/bluebanquise/bluebanquise/blob/2b0572ff796a133856ecd455e6d8c5b6f9dce094/resources/packaging/bluebanquise.spec#L1) would need to be updated the day of the release.

**Comment by oxedions** [comment]
Updated tasks for 1.4, do not hesitate to add/comment. These are idea.

**Comment by oxedions** [comment]
I am closing this issue, since we now have projects and discussions enabled.
